#ifndef HEADER_SRC_CONFIG_H_INCLUDED
#define HEADER_SRC_CONFIG_H_INCLUDED

#define APPLICATION_NAME "NewProject1"
#define APPLICATION_CODENAME "123"
#define APPLICATION_COPYRIGHT_YEARS "123"
#define APPLICATION_VERSION_MAJOR 0
#define APPLICATION_VERSION_MINOR 1

#define APPLICATION_VENDOR_ID "123"
#define APPLICATION_VENDOR_NAME "123"
#define APPLICATION_VENDOR_URL "123"

#define APPLICATION_ID "123"


#endif
